export const CHAT_THREADS = [
  {
    id: '1',
    name: 'Alene',
    preview: 'Need the latest invoice summary before EOD.',
    time: '11:30 AM',
    unread: true,
    unreadCount: 2,
    favorite: false,
    group: false,
    online: true,
    initials: 'AL',
  },
  {
    id: '2',
    name: 'Keefe',
    preview: 'Shared the updated dashboard mockups.',
    time: '10:12 AM',
    unread: true,
    unreadCount: 1,
    favorite: true,
    group: false,
    online: true,
    initials: 'KE',
  },
  {
    id: '3',
    name: 'Lazaro',
    preview: 'Can we sync on the rollout plan?',
    time: 'Yesterday',
    unread: false,
    unreadCount: 0,
    favorite: false,
    group: false,
    online: false,
    initials: 'LA',
  },
  {
    id: '4',
    name: 'Product Team',
    preview: 'Maya: Sprint review moved to Friday.',
    time: 'Yesterday',
    unread: false,
    unreadCount: 0,
    favorite: false,
    group: true,
    online: false,
    initials: 'PT',
  },
  {
    id: '5',
    name: 'Jenny Willson',
    preview: 'Thanks — looks good to me.',
    time: 'Mon',
    unread: false,
    unreadCount: 0,
    favorite: true,
    group: false,
    online: true,
    initials: 'JW',
  },
]

export const NOTIFICATIONS = [
  {
    id: '1',
    name: 'Cristina Danny',
    message: 'mentioned you in Mantis',
    time: '12 min ago',
    category: 'Project',
    unread: true,
    mention: true,
    initials: 'CD',
  },
  {
    id: '2',
    name: 'Aida Burg',
    message: 'joined Final Presentation',
    time: '2h ago',
    category: 'Meetup',
    unread: true,
    mention: false,
    initials: 'AB',
  },
  {
    id: '3',
    name: 'Jenny Willson',
    message: 'is requesting to Upgrade Plan',
    time: '3h ago',
    category: 'Billing',
    unread: true,
    mention: false,
    initials: 'JW',
    actions: ['accept', 'decline'],
  },
  {
    id: '4',
    name: 'Robert Fox',
    message: 'upload a file',
    time: '1d ago',
    category: 'Files',
    unread: false,
    mention: false,
    initials: 'RF',
    attachment: { name: 'mantis_dashboard.fig', size: '26mb' },
  },
  {
    id: '5',
    name: 'Emily',
    message: 'sent you reply',
    time: '1d ago',
    category: 'Message',
    unread: false,
    mention: true,
    initials: 'EM',
    replyPreview: 'We have scheduled a meeting for Thursday at 3 PM. Please confirm your availability.',
  },
  {
    id: '6',
    name: 'Jenny Willson',
    message: 'commented on Small Business',
    time: '2d ago',
    category: 'Social',
    unread: false,
    mention: false,
    initials: 'JW',
  },
  {
    id: '7',
    name: 'Robert Fox',
    message: 'invited you to chat',
    time: '2d ago',
    category: 'Chat',
    unread: false,
    mention: false,
    initials: 'RF',
  },
  {
    id: '8',
    name: 'Maya',
    message: 'mentioned you in Sprint Review',
    time: '3d ago',
    category: 'Project',
    unread: true,
    mention: true,
    initials: 'MY',
  },
]
